import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { signIn, signOut, useSession } from "next-auth/react";
import { unstable_getServerSession } from "next-auth";
import { oktaOptions } from "./api/auth/[...nextauth]";
import { redirect } from "next/dist/server/api-utils";
export async function getServerSideProps(context: any) {
  const session: any = await unstable_getServerSession(
    context.req,
    context.res,
    oktaOptions
  );
  if (session && session.user.groups.includes("admins")) {
    return {
      redirect: { destination: "/admin", permanent: false },
    };
  }
  return { props: { } }
}
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href="admin">Admin</a>
      <div>
        <button onClick={() => signIn("okta")}>Sign in</button>
        <button onClick={() => signOut()}>Sign out</button>
      </div>
    </div>
  );
};

export default Home;
